
public enum TokenType {
	NOSYM, IDENT, EOF, EOL, PRINT, INPUT, IF, ELSE, WHILE, FOR, INTNUM, REALNUM,
	PLUS, MINUS, MULT, DIVD, ASSIGNMENT, EQUALS, LSS, GTR, COMMA,
	LPAREN, RPAREN, SEMICOLON, LITERAL, DOUBLEQUOTE, STOP, INT
}
